### ISSUE TITLE
Shared library error when running npx crusher.dev on WSL

### ISSUE THREAD

**Issue by joshgrift** [crusher-dev/crusher#351]
### Version

v0.5.11

### Platform

Linux DESKTOP-RP8H596 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### What steps will reproduce the bug?

execute `npx crusher.dev` on WSL 2

### What is the expected behavior?

Crusher should run!

### Additional information

I'm using Ubuntu 22 on Windows via WSL

**Comment by utkarsh-dixit** [comment]
Hey @joshgrift,
Thanks for reporting this issue. Crusher does work with Ubuntu 22.04, but we haven't tried it with WSL. Will take a look at it later today

**Comment by utkarsh-dixit** [comment]
Finally tried it out on ubuntu WSL today and managed to make it work after facing some errors ([Loom here](https://www.loom.com/share/08a9079a81ae4efda56bc85ea451d0f2))

- CLI was not able to unzip because `unzip` is not installed. Fixed by `apt install unzip`
- Was getting `libnss3.so: cannot open shared object file: No such file or directory`. Fixed by installing `google-chrome`, which will also install the required dependencies.

@joshgrift Let me know if this works for you

**Comment by joshgrift** [comment]
Works!
